# Generated by Django 5.2 on 2025-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_admin', '0002_profile_credits_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=6),
        ),
    ]
